add_newline = true
command_timeout = 5000
format = "$shell$os$directory$nix_shell$line_break$sudo$character$command_timeout"
palette = "catppuccin_frappe"
right_format = "$cmd_duration$time"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"
vimcmd_symbol = "[V](bold red)"

[directory]
fish_style_pwd_dir_length = 1
format = "in [$path]($style) "
truncate_to_repo = false
truncation_symbol = "../"

[nix_shell]
disabled = false
format = "inside \\( $state\\) "
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
style = "bold blue"
unknown_msg = "[unknown shell](bold yellow)"

[os]
disabled = false
style = "bold blue"

[os.symbols]
Linux = " "
Macos = "󰀵 "
NixOS = "󱄅 "

[palettes.catppuccin_frappe]
base = "#303446"
blue = "#8caaee"
crust = "#232634"
flamingo = "#eebebe"
green = "#a6d189"
lavender = "#babbf1"
mantle = "#292c3c"
maroon = "#ea999c"
mauve = "#ca9ee6"
overlay0 = "#737994"
overlay1 = "#838ba7"
overlay2 = "#949cbb"
peach = "#ef9f76"
pink = "#f4b8e4"
red = "#e78284"
rosewater = "#f2d5cf"
sapphire = "#85c1dc"
sky = "#99d1db"
subtext0 = "#a5adce"
subtext1 = "#b5bfe2"
surface0 = "#414559"
surface1 = "#51576d"
surface2 = "#626880"
teal = "#81c8be"
text = "#c6d0f5"
yellow = "#e5c890"

[shell]
bash_indicator = "\\$"
disabled = false
fish_indicator = "λ"
format = "\\[[$indicator]($style)\\] "
nu_indicator = ">"
powershell_indicator = ">_"
style = "cyan bold"
zsh_indicator = "%"

[sudo]
disabled = false
style = "bold red"
symbol = " "

[time]
disabled = false
format = "at [$time]($style) "
style = "bold blue"
time_format = "%X"
